parameters:
- name: environmentName
- name: azureServiceConnection
- name: webAppName
- name: acrLoginServer
- name: imageRepository
- name: imageTag

jobs:
- deployment: Deploy_${{ parameters.environmentName }}
  displayName: Deploy to ${{ parameters.environmentName }}
  environment: ${{ parameters.environmentName }}
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    runOnce:
      deploy:
        steps:
        - task: AzureWebAppContainer@1
          displayName: 'Deploy Container to Azure Web App: ${{ parameters.webAppName }}'
          inputs:
            azureSubscription: ${{ parameters.azureServiceConnection }}
            appName: ${{ parameters.webAppName }}
            imageName: '${{ parameters.acrLoginServer }}/${{ parameters.imageRepository }}:${{ parameters.imageTag }}'
