parameters:
- name: environmentName
- name: azureServiceConnection
- name: webAppName
- name: targetAcrConnection
- name: targetAcrLoginServer
- name: imageRepository
- name: imageTag
- name: promoteImage
  type: boolean
  default: false
- name: sourceAcrConnection
  type: string
  default: ''
- name: sourceAcrLoginServer
  type: string
  default: ''

jobs:
- deployment: Deploy_${{ parameters.environmentName }}
  displayName: Deploy to ${{ parameters.environmentName }}
  environment: ${{ parameters.environmentName }}
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    runOnce:
      deploy:
        steps:
        # Conditionally run the promotion steps if promoteImage is true
        - ${{ if eq(parameters.promoteImage, true) }}:
          - template: promote-acr.yaml
            parameters:
              sourceAcrConnection: ${{ parameters.sourceAcrConnection }}
              sourceAcrLoginServer: ${{ parameters.sourceAcrLoginServer }}
              targetAcrConnection: ${{ parameters.targetAcrConnection }}
              targetAcrLoginServer: ${{ parameters.targetAcrLoginServer }}
              imageRepository: ${{ parameters.imageRepository }}
              imageTag: ${{ parameters.imageTag }}

        # Deploy the container to the App Service using the Target ACR
        - task: AzureWebAppContainer@1
          displayName: 'Deploy Container to Azure Web App: ${{ parameters.webAppName }}'
          inputs:
            azureSubscription: ${{ parameters.azureServiceConnection }}
            appName: ${{ parameters.webAppName }}
            imageName: '${{ parameters.targetAcrLoginServer }}/${{ parameters.imageRepository }}:${{ parameters.imageTag }}'
